#! /bin/sh
CONTENT="icons images _locales manifest.json options README.rst"
RE='^\s*"version"\s*:\s*"\([0-9\.]\+\(-\w\+\)\?\)"\s*,\s*$'

VERSION=`grep "$RE" manifest.json | sed -e "s|$RE|\1|g"`

if [ ! -z "$VERSION" ]; then
  XPI="resubmit-${VERSION}.xpi"
else
  XPI="resubmit.xpi"
fi

echo -n "build-xpi: building ${XPI}... "
if zip -r "${XPI}" $CONTENT > /dev/null; then
  echo "done."
else
  echo "failed."
fi
